GET http://localhost:5000/api/accounts/USR-0003
### 
GET http://localhost:5000/api/accounts/Damien
###
POST http://localhost:5000/api/accounts
Content-Type: application/json

{
    "id": "USR-0003",
    "firstName": "maud", 
    "lastName": "Tata",
    "age": 19,
    "sex": "féminin",
    "hobbie": ["danse, cuisine"],
    "address": "12, rue de Nemours",
    "city": "Rennes"
}
###
PUT http://localhost:5000/api/accounts/USR-0003
Content-Type: application/json

{
    "address": "81 Rue Ange Blaize"
}
###
DELETE http://localhost:5000/api/accounts/USR-0003